# Setup
title:          "村田 光春"
paginate:       5
sass:
  style:        compressed
host:           localhost # same as default value '127.0.0.1' but reads better
assets:
  css:
    # Use https://www.srihash.org to generate the hash, or use the hash from upstream
    uri:         "https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
    sri:         "sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l"

github_org:      "https://github.com/himeyama"
defaults:
  - scope:
      path:     ""
    values:
      image:
        path:   "/assets/img/bootstrap-social.png" # default image
        width:  1000
        height: 500

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

redirect_from:
  json: false
